version: '2'
services:
  jhsampleapplication-app:
    image: jhsampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://jhsampleapplication-mariadb:3306/jhsampleapplication
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 45677:45677
  jhsampleapplication-mariadb:
    extends:
      file: mariadb.yml
      service: jhsampleapplication-mariadb
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
